# Environment
dist: bionic
language: java

# Setup the artifact signing key; it will be used to publish snapshots and releases
before_install:
  - gpg2 --batch --no-default-keyring --allow-secret-key-import --import < ${ARTIFACT_SIGNING_KEY}

# Deploy snapshot build
script: build/deploy.sh

# Deploy release build
deploy:
  on:
    tags: true
  provider: script
  script: build/release.sh
