# Environment
dist: bionic
language: java

# Setup the artifact signing key; it will be used to publish snapshots and releases
before_script:
  - openssl aes-256-cbc -K $encrypted_59cd562a81f9_key -iv $encrypted_59cd562a81f9_iv
    -in .mvn/artifact-signing-key.asc.enc -out .mvn/artifact-signing-key.asc -d
  - gpg2 --batch --no-default-keyring --allow-secret-key-import --import .mvn/artifact-signing-key.asc

# Deploy snapshot build to OSSRH
script: ./mvnw deploy -settings .mvn/settings.xml -P ossrh

# Deploy release build
deploy:
  - on:
      tags: true
    provider: script
    script: ./mvnw versions:set -DnewVersion=${TRAVIS_TAG}
  - on:
      tags: true
    provider: script
    script: ./mvnw deploy -settings .mvn/settings.xml -P ossrh
