if: branch !~ /^(release)/

# Host Environment
os: linux

# Build Environment
dist: bionic
language: java
cache:
  directories:
    - $HOME/.m2

# Prerequisites
before_install:
  # Set up path
  - export PATH=${PATH}:.
  # Setup the code signing key; it will be used to publish snapshots and releases
  - openssl aes-256-cbc -K $encrypted_59cd562a81f9_key -iv $encrypted_59cd562a81f9_iv
    -in deploy/code-signing-key.asc.enc -out /tmp/code-signing-key.asc -d
  - gpg --batch --no-default-keyring --allow-secret-key-import --import /tmp/code-signing-key.asc
  # Setup the github deploy key as the default SSH key
  - openssl aes-256-cbc -K $encrypted_59cd562a81f9_key -iv $encrypted_59cd562a81f9_iv
    -in deploy/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 400 ~/.ssh/id_rsa
  # Configure git
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@travis-ci.com"
  - git remote add ssh-origin git@github.com:${TRAVIS_REPO_SLUG}.git

# Pre-download all maven dependencies
install: mvnw -e -B -ntp -settings .mvn/settings.xml -P ossrh dependency:go-offline

# Integrate the latest and deploy snapshot artifacts to OSSRH. The script
# returns a success exit code to ensure build proceeds to deploy stage
script: deploy/deploy-branch.sh

# Perform a release when the repository has been tagged
deploy:
  - provider: script
    script: deploy/release-tag.sh
    skip_cleanup: true
    on:
      tags: true
